### ISSUE TITLE
'ld_prune' function

### ISSUE THREAD

**Issue by jenifferteles** [TheWangLab/algatr#42]
Hello, I am unable to use the 'ld_prune' function; the following error occurs: Could not find the 'ld_prune' function.

**Comment by eachambers** [comment]
Hi Jeniffer,

Thanks for bringing this to our attention. It looks like the `ld_prune()` function wasn't exported properly; this should now be fixed but please do let me know if it's still causing you problems.

Thanks,
Anne

**Comment by jenifferteles** [comment]
Hi, E. Anne Chambers. Thank you so much for the quick response. I uninstalled and reinstalled the package. And now this error has appeared: 
Error in here(paste(out_name, "_LDpruned", sep = "")) : 
  Could not find the 'here' function.

I didn't undertand why the "here" function appears. I used this command: 

vcf_ldpruned <- ld_prune (vcf = "Fbra_r65.snps.vcf", out_name = "Fbra_ldpruned", out_format = "vcf", ld.threshold = 0.9, slide.max.n = 10)

**Comment by eachambers** [comment]
The `ld_prune()` function uses the here package internally. Try to install the here package (available on CRAN so you can just do the usual `install.packages("here")` and then `library(here)`. The here package is a required import for algatr so it should have prompted you to install the package when you installed algatr. Let me know if installing (and loading) here and then running `ld_prune()` works for you.

Anne

**Comment by eachambers** [comment]
Great-- thanks!

**Comment by ioanaanghel** [comment]
Hello!

I am having a similar issue. I am trying to use ld_prune on a cluster in a docker container, it cannot find the function, even though algatr and here (and all the other libraries) are loaded: 
 
>` ld_prune(vcf = "77-Linanthus.prunedLIPA_27indiv.vcf", out_name = "lipa27", out_format = "vcf", ld.threshold = 0.9, slide.max.n = 10)`
_Error in ld_prune(vcf = "77-Linanthus.prunedLIPA_27indiv.vcf", out_name = "lipa27",  : 
  could not find function "ld_prune"_


And in parallel, I am trying to run it on a smaller dataset on my computer. I get this error when running ld_prune:

> `ld_prune(vcf = "77-Linanthus.prunedLIPA_27indiv.vcf", out_name = "lipa27", out_format = "vcf", ld.threshold = 0.9, slide.max.n = 10)`
_Error in loadNamespace(x) : there is no package called ‘SeqArray’_

And this error when I try to install SeqArray:
`BiocManager::install("SeqArray")`
_Old packages: 'qvalue'_


Do you have any suggestions? 

Thank you!

**Comment by AnushaPB** [comment]
Hello!

You may need to rebuild your Docker image from scratch to make sure that the latest version of algatr has been installed. One way to check that this is the issue is to try and install algatr within your current Docker container and see if `ld_prune()` is recognized after manually installing the latest algatr version (i.e. check by running `library(algatr); ?ld_prune` after reinstalling algatr). You can also build your Docker image off of our official algatr image which you can find [here](https://github.com/TheWangLab/algatr/pkgs/container/algatr).

With regard to the issue on your own computer, what happens when you try to install qvalue separately first (i.e., 
`BiocManager::install("qvalue")`) and then install SeqArray?

**Comment by ioanaanghel** [comment]
Hi Anusha, thanks for your help! Somehow this specific issue was resolved after reinstalling various required packages. I appreciate your prompt response!

I am still having a lot of trouble with package incompatibilities. Right now I am getting this error when running `tess_krig()`, with my data as well as with the lizard example dataset: 

```
> krig_admix <- tess_krig(qmat, coords_proj, krig_raster)
Error in (function (cond)  : 
  error in evaluating the argument 'x' in selecting a method for function 'rast': ℹ In index: 1.
Caused by error:
! package slot missing from signature for generic ‘coerce’
and classes STFDF, RasterBrick
cannot use with duplicate class names (the package may need to be re-installed)
```
I tried reinstalling raster and terra, loading them in different orders, restarting R session, and various combinations of those things.
Are you getting this error when running it on your end? 

Thank you so much@

**Comment by AnushaPB** [comment]
No, I can't seem to replicate your error. Is it possible that you need to update your R version? 
Here are a couple of possibly related issues I found online:
https://github.com/r-spatial/gstat/issues/15
https://stackoverflow.com/questions/73692206/package-gwmodel-fails-to-load

**Comment by ioanaanghel** [comment]
Thanks, I have a workaround by working in base R instead of R studio for now, still couldn't find the solution for R studio but that's fine. Thanks for your suggestions!

**Comment by AnushaPB** [comment]
I would maybe check to see which R install/version your RStudio is linked too (https://stackoverflow.com/questions/61093953/how-to-view-change-the-installation-of-r-that-rstudio-uses). Anything that works in base R should work in RStudio, if they are linked to the same R install, since RStudio is just a developer environment that utilizes an R install you have.
