### ISSUE TITLE
tess_ktest error

### ISSUE THREAD

**Issue by jenifferteles** [TheWangLab/algatr#43]
Hi Anne, sorry to bother you again. I found another issue, if you could help me, please. I tried running tess_ktest, and this error appeared

> tess3_result<- tess_ktest(Fbra_dosage, Fbra_coords, Kvals = 1:4, ploidy = 2, K_selection = "auto")

Erro: 'tess3' is not an exported object from 'namespace:tess3r'

What should I do? thanks

**Comment by eachambers** [comment]
Hi Jeniffer,

No need to apologize. Can you ensure that you have the tess3r package installed and updated (and it's installed from the correct repository, which is this: https://github.com/bcm-uga/TESS3_encho_sen; the reason I say this is because there's another tess3 repository that's now deprecated). One way to make sure you've got all the necessary packages for any of algatr's methods is to use the `x_packages()` functions, so in this case you could run `tess_packages()` and that should prompt the installation and loading of the correct tess3r.

Let me know...

Anne

**Comment by jenifferteles** [comment]
It worked, thank you so much. Great job on this package, I'm loving it. Best regards

**Comment by eachambers** [comment]
Great! Glad you're enjoying the package!
