### ISSUE TITLE
tess_ktest fails with multiple chromosomes

### ISSUE THREAD

**Issue by renhamm** [TheWangLab/algatr#54]
When I run tess_ktest on one chromosome, everything works fine, but when I run the exact same command on my multi-chromosome file, it fails with the following error:

Error in if (rmse[r] < rmse.max) { :
  missing value where TRUE/FALSE needed

This is my call:
tess3_result <- tess_ktest(simple_dos, coords, Kvals = 1:10, ploidy = 2, K_selection = "auto")

Neither of the two user-offered inputs (simple_dos and coords) have any NAs, so I'm not sure what this is referring to by missing values. How do I fix this?

**Comment by eachambers** [comment]
Hi Ren,

Firstly, it's worth noting that this is actually an error within TESS3, not with algatr. We've encountered this error when we've tried to run massive datasets (i.e., >1M SNPs). How big is your dataset? You might try subsampling it and seeing if you can replicate the error. Otherwise, we've found non spatially explicit methods like ADMIXTURE to run very quickly when working with large WGS datasets.

Anne
