### ISSUE TITLE
GDM error with vignette

### ISSUE THREAD

**Issue by ptitle** [TheWangLab/algatr#78]
Hi,
I've been walking through the excellent vignettes provided with this R package. For the GDM vignette with model selection, when I run the following:

```
gdm_best <- gdm_run(gendist = liz_gendist, 
                    coords = liz_coords, 
                    env = env, 
                    model = "best", 
                    scale_gendist = TRUE,
                    nperm = 1000, 
                    sig = 0.05)
```
I ultimately get an error `Error in gdm::gdm.varImp(gdmData, geo = FALSE, splines = NULL, nPerm = nperm,  : 
  Only one predictor remains...variable assessment stopped.`

In case this had to do with insufficient permutations, I increased that to 5000, but still get the same error.

Is there something I need to adjust on my end? Or is this indicative of some underlying bug?

Thanks so much!

**Comment by eachambers** [comment]
Hi,

Thanks for reaching out. When you get that error message from GDM, it's always a good idea to increase the number of permutations (as you did). However, in the case of algatr's example dataset, there are no predictor variables are significantly associated with genetic distances, which is why you get the message `"Only one predictor remains"`. This is also why the vignette doesn't actually run those lines of code; we simply provided them so users could see what an example call to `gdm_run()` would look like with variable selection.

Let me know if you have any other questions!

Best,
Anne

**Comment by ptitle** [comment]
Ah, I see now that this is stated in the vignette. Thanks for the quick response and sorry for the trouble!
