### ISSUE TITLE
Memory problem select_k()

### ISSUE THREAD

**Issue by bryonylb** [TheWangLab/algatr#79]
Hi, I am running my R script on a cluster and have received this error:

Error: protect(): protection stack overflow
Execution halted
Warning message:
system call failed: Cannot allocate memory

This appears when I run the line: 

kVal <- select_K(gen, K_selection = "tracy_widom", criticalpoint = 2.0234)

I have already read in the environment variables and the coordinates. I've also read in the VCF file and converted it to a dosage matrix, which returns the following:

> catVCF <- read.vcfR("catharsius_filtered.vcf")
Scanning file to determine attributes.
File attributes:
  meta lines: 603850
  header_line: 603851
  variant count: 233804
  column count: 76
Meta line 603850 read in.
All meta lines processed.
gt matrix initialized.
Character matrix gt created.
  Character matrix gt rows: 233804
  Character matrix gt cols: 76
  skip: 0
  nrows: 233804
  row_num: 0
Processed variant: 233804
All variants processed
> setwd(resultsWd)
> gen <- vcf_to_dosage(catVCF)
> gen <- simple_impute(gen)

There is plenty of memory allocated to the job in the cluster, so I think it is to do with the code. Thanks for your help.

**Comment by AnushaPB** [comment]
The "protection stack overflow" error in R typically occurs due to R's internal memory protection mechanism rather than system memory allocation, even when sufficient RAM is available, so unfortunately there is not much we can do on our end.

You can try increasing R's protection stack size by adding this line before running your analysis:
```r
options(expressions = 500000)
```
Additionally, you can try increasing the maximum stack size when you launch R from the command line:
```bash
R --max-ppsize=500000
```
Or within your cluster job script:
```bash
export R_MAX_PPSIZE=500000
R CMD BATCH your_script.R
```
