### ISSUE TITLE
GDM mapping function bug

### ISSUE THREAD

**Issue by ptitle** [TheWangLab/algatr#82]
Hi,

I get the following error with gdm_map().

```
library(algatr)
library(raster)
library(terra)
library(viridis)
library(gdm)

load_algatr_example()

env <- raster::extract(CA_env, liz_coords)

gdm_full <- gdm_run(
  gendist = liz_gendist,
  coords = liz_coords,
  env = env,
  model = "full",
  scale_gendist = TRUE
)

map <- gdm_map(gdm_full$model, CA_env, liz_coords)

Error in svd(x, nu = 0, nv = k) : a dimension is zero
In addition: Warning message:
[readValues] raster has no values
```

The reason is that line 383 of GDM.R has: `rastTrans <- terra::rast(rastTrans)` which erases all values in the rasters. And that leads to problems in the subsequent code. 

Removing that line seems to solve the problem.

**Comment by AnushaPB** [comment]
Thanks for bringing our attention to this! It looks like a recent GDM update changed the output of `gdm.transform()` from a raster object to a SpatRaster object, which is why `terra::rast()` now erases the values. I have updated the code to resolve this issue and will push it in the next 24 hours once it passes our checks. Please let us know if you encounter any other issues with GDM!

**Comment by ptitle** [comment]
Works now! Thanks!
